name: 'Google Drive Find File'
description: 'Search for a file on Google Drive'
inputs:
  credentials:
    description: 'Google service account credentials'
    required: true
  parent-folder-id:
    description: 'Id of the drive folder to search'
    required: true
  filename:
    description: 'Filename to search'
    required: true
outputs:
  exists:
    description: 'true if the file exists on the specified drive'
runs:
  using: 'node16'
  main: 'dist/index.js'
